### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'cmd'

### ISSUE THREAD

**Issue by iichelhadi** [griffithlab/pVACtools#672] opened 2021-05-14 14:34 UTC
* pvactools version:2.0.2
* Python version:3.8.5
* Operating System: Centos

I get the following error while running `pvacseq run` after the run seems to have processed quite a bit:
`TypeError: __init__() missing 1 required positional argument: 'cmd'`

The command I run is the following:

mkdir pvacseq/
pvacseq run --iedb-install-directory /home/svu/phaei/IEDB \
	--binding-threshold 500 --n-threads 24 \
	--net-chop-method "cterm" --netmhc-stab --exclude-NAs \
	--normal-sample-name ${patient_ID}_N \
	vcf_files/${patient_ID}_somatic.filtered.VEP.vcf \
	${patient_ID}_T ${allele_1},${allele_2} \
	MHCflurry MHCnuggetsI NetMHC NetMHCpan pvacseq3/

where ${patient_ID}, ${allele_1},${allele_2} are variables read from a file in a while loop

**Log Output**

```
Making binding predictions on Allele HLA-A*24:07 and Epitope Length 11 with Method NetMHCpan - File /hpctmp/phaei/MUX11418/EXOME/pvacseq2/2432/MHC_Class_I/tmp/2432_T.netmhcpan.HLA-A*24:07.11.tsv_3401-3600 - Completed
Making binding predictions on Allele HLA-A*24:07 and Epitope Length 11 with Method NetMHCpan - File /hpctmp/phaei/MUX11418/EXOME/pvacseq2/2432/MHC_Class_I/tmp/2432_T.netmhcpan.HLA-A*24:07.11.tsv_9401-9600 - Completed
Making binding predictions on Allele HLA-A*24:07 and Epitope Length 10 with Method NetMHCpan - File /hpctmp/phaei/MUX11418/EXOME/pvacseq2/2432/MHC_Class_I/tmp/2432_T.netmhcpan.HLA-A*24:07.10.tsv_24601-24800 - Completed
An exception occured in thread 0: (<class 'subprocess.CalledProcessError'>, Command '['/nfs/app1/bioinfo/miniconda/4.9/bin/python', '/home/svu/phaei/IEDB/mhc_i/src/predict_binding.py', 'netmhcpan', 'HLA-A*24:07', '8', '/hpctmp/phaei/MUX11418/EXOME/pvacseq2/2432/MHC_Class_I/tmp/2432_T.8.fa.split_1-200']' returned non-zero exit status 2.).
Traceback (most recent call last):
  File "/home/svu/phaei/.local/lib/python3.8/site-packages/lib/pipeline.py", line 373, in call_iedb
    lib.call_iedb.main(arguments)
  File "/home/svu/phaei/.local/lib/python3.8/site-packages/lib/call_iedb.py", line 41, in main
    raise err
  File "/home/svu/phaei/.local/lib/python3.8/site-packages/lib/call_iedb.py", line 36, in main
    (response_text, output_mode) = prediction_class_object.predict(args.input_file, args.allele, args.epitope_length, args.iedb_executable_path, args.iedb_retries)
  File "/home/svu/phaei/.local/lib/python3.8/site-packages/lib/prediction_class.py", line 58, in predict
    response = run(arguments, stdout=response_fh, check=True)
  File "/nfs/app1/bioinfo/miniconda/4.9/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/nfs/app1/bioinfo/miniconda/4.9/bin/python', '/home/svu/phaei/IEDB/mhc_i/src/predict_binding.py', 'netmhcpan', 'HLA-A*24:07', '8', '/hpctmp/phaei/MUX11418/EXOME/pvacseq2/2432/MHC_Class_I/tmp/2432_T.8.fa.split_1-200']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/svu/phaei/.local/bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "/home/svu/phaei/.local/lib/python3.8/site-packages/tools/pvacseq/main.py", line 95, in main
    args[0].func.main(args[1])
  File "/home/svu/phaei/.local/lib/python3.8/site-packages/tools/pvacseq/run.py", line 122, in main
    pipeline.execute()
  File "/home/svu/phaei/.local/lib/python3.8/site-packages/lib/pipeline.py", line 475, in execute
    self.call_iedb(chunks)
  File "/home/svu/phaei/.local/lib/python3.8/site-packages/lib/pipeline.py", line 374, in call_iedb
    p.print("Making binding predictions on Allele %s and Epitope Length %s with Method %s - File %s - Completed" % (a, epl, method, filename))
  File "/home/svu/phaei/.local/lib/python3.8/site-packages/pymp/__init__.py", line 148, in __exit__
    raise exc_t(exc_val)
TypeError: __init__() missing 1 required positional argument: 'cmd'
```

I hope to hear get a response soon
kind regards

**Comment by iichelhadi** [comment] 2021-05-14 23:17
quick update. the script doesn't not seem to run when I use it in the the while loop to fill in the variables (error posted) however when I fill in the variables manually it works fine. Does someone understand why that is? I am trying to automate the prediction process in my script.
regards

**Comment by susannasiebert** [comment] 2021-05-17 14:04
can you echo the pvacseq command in your script instead of running it to check the command created by your while loop? 

I believe the error you are seeing might be intermittent and not necessarily connected to whether or not you're using a script. If your script was incorrect, I would expect you to not be able to run pVACseq at all but it is running and only some of of the calls to IEDB are failing. For some resource-intensive IEDB prediction algorithms this sort of error is usually caused by running out of memory. You could try reducing the number of threads or running on a machine with higher RAM. If you script is starting multiple pvacseq runs for multiple patients, that can also be the problem as those are competing for compute resources.

**Comment by susannasiebert** [comment] 2021-08-03 15:40
I'm closing this issue since there hasn't been any further activity but do feel free to reopen if you're still running into this problem.

**Closed by susannasiebert** 2021-08-03 15:40 UTC

**Comment by iichelhadi** [comment] 2021-08-04 01:55
> I'm closing this issue since there hasn't been any further activity but do feel free to reopen if you're still running into this problem.

I still don't have a solution so just repeated the lines of code. It works for now. Thnx
