### ISSUE TITLE
Exception: An error occurred while calling MHCflurry

### ISSUE THREAD

**Issue by hliu2016** [griffithlab/pVACtools#622] opened 2020-12-20 01:00 UTC
Hi, I am running the docker image of pvactools. I think the MHCflurry is correctly installed. But when I test the example data downloaded by running the pvacseq download_example_data command, I run into this error:

> (base) root@7730a315332d:/opt/data# pvacseq run pvacseq_example_data/input.vcf H_NJ-HCC1395-HCC1395 HLA-A*02:01,HLA-B*35:01 MHCflurry MHCnuggetsII NetMHCpan output -e 8,9,10 --iedb-install-directory /opt/iedb/
> mesg: ttyname failed: No such file or directory
> Executing MHC Class I predictions
> Converting .vcf to TSV
> Completed
> Splitting TSV into smaller chunks
> Splitting TSV into smaller chunks - Entries 1-64
> Completed
> Generating Variant Peptide FASTA and Key Files
> Generating Variant Peptide FASTA and Key Files - Entries 1-128
> Completed
> Making binding predictions on Allele HLA-A*02:01 and Epitope Length 8 with Method MHCflurry - File /opt/data/output/MHC_Class_I/tmp/H_NJ-HCC1395-HCC1395.MHCflurry.HLA-A*02:01.8.tsv_1-128
> An exception occured in thread 0: (<class 'Exception'>, An error occurred while calling MHCflurry:
> ).
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.6/site-packages/lib/prediction_class.py", line 261, in predict
>     response = run(arguments, check=True, stdout=DEVNULL, stderr=stderr_fh)
>   File "/opt/conda/lib/python3.6/subprocess.py", line 418, in run
>     output=stdout, stderr=stderr)
> subprocess.CalledProcessError: Command '['mhcflurry-predict', '--alleles', 'HLA-A*02:01', '--out', '/tmp/tmpyzlges8z', '--peptides', 'LPLPPPPL', 'PLPPPPLL', 'LPPPPLLP', 'PPPPLLPL', 'PPPLLPLL', 'PPLLPLLL', 'PLLPLLLL', 'LLPLLLLL', 'LPLLLLLL', 'PLLLLLLG', 'LLLLLLGA', 'LLLLLGAS', 'LLLLGASG', 'LLLGASGG']' died with <Signals.SIGILL: 4>.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.6/site-packages/lib/pipeline.py", line 342, in call_iedb
>     lib.call_iedb.main(arguments)
>   File "/opt/conda/lib/python3.6/site-packages/lib/call_iedb.py", line 55, in main
>     raise err
>   File "/opt/conda/lib/python3.6/site-packages/lib/call_iedb.py", line 50, in main
>     (response_text, output_mode) = prediction_class_object.predict(args.input_file, args.allele, args.epitope_length, args.iedb_executable_path, args.iedb_retries)
>   File "/opt/conda/lib/python3.6/site-packages/lib/prediction_class.py", line 267, in predict
>     raise Exception("An error occurred while calling MHCflurry:\n{}".format(err))
> Exception: An error occurred while calling MHCflurry:
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/conda/bin/pvacseq", line 8, in <module>
>     sys.exit(main())
>   File "/opt/conda/lib/python3.6/site-packages/tools/pvacseq/main.py", line 95, in main
>     args[0].func.main(args[1])
>   File "/opt/conda/lib/python3.6/site-packages/tools/pvacseq/run.py", line 171, in main
>     pipeline.execute()
>   File "/opt/conda/lib/python3.6/site-packages/lib/pipeline.py", line 443, in execute
>     self.call_iedb(chunks)
>   File "/opt/conda/lib/python3.6/site-packages/lib/pipeline.py", line 343, in call_iedb
>     p.print("Making binding predictions on Allele %s and Epitope Length %s with Method %s - File %s - Completed" % (a, epl, method, filename))
>   File "/opt/conda/lib/python3.6/site-packages/pymp/__init__.py", line 148, in __exit__
>     raise exc_t(exc_val)
> Exception: An error occurred while calling MHCflurry:
>

I have no idea about this error. Is there any way to solve it?

**Comment by susannasiebert** [comment] 2020-12-21 15:45
Unfortunately, I'm unable to reproduce this error both on version 1.5.11 and 1.5.12 (inside Docker). Which version of the Docker container are you using?

Could you try to execute the following MHCflurry command directly and see if that gives us a more descriptive error message:

**Comment by susannasiebert** [comment] 2020-12-21 15:49
Unfortunately, I'm unable to reproduce this error both on version 1.5.11 and 1.5.12 (inside Docker). Which version of the Docker container are you using?

Could you try to execute the following MHCflurry command directly and see if that gives us a more descriptive error message:
```
mhcflurry-predict --alleles HLA-A*02:01 --out /tmp/tmpyzlges8z --peptides LPLPPPPL PLPPPPLL LPPPPLLP PPPPLLPL PPPLLPLL PPLLPLLL PLLPLLLL LLPLLLLL LPLLLLLL PLLLLLLG LLLLLLGA LLLLLGAS LLLLGASG LLLGASGG
```

**Comment by susannasiebert** [comment] 2020-12-21 22:57
I also just released version 1.5.13 with some improvements to the way we use MHCflurry so I would recommend trying it with this version and see if that leads to a different result.

**Comment by hliu2016** [comment] 2020-12-22 13:45
@susannasiebert 
Thank you for your response. I have solved this problem. This is caused by tensorflow.

**Comment by susannasiebert** [comment] 2020-12-22 15:32
Glad you were able to find the problem. Could you share what about tensorflow was causing this issue and how you resolved it so that we can help other issues that might encounter this problem in the future?

**Comment by susannasiebert** [comment] 2021-02-10 14:58
@hliu2016 I would still be interested to know more about how you were able to resolve this issue so that we can better assist other users with this problem in the future. I will close this issue but do feel free to comment with this information at your convenience.

**Closed by susannasiebert** 2021-02-10 14:58 UTC
