### ISSUE TITLE
Error caused by shell and conda

### ISSUE THREAD

**Issue by pfren1998** [griffithlab/pVACtools#474] opened 2019-12-02 10:03 UTC
Hi
Recently I am testing my pipeline on a ubuntu server, but I have to stop when I meet the error which is caused by shell and conda. However, I run pvacseq successfully on a centos cluster. I wonder is there any method could help me out of the problem? 

**Below is the error content on the ubuntu server:**

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

Traceback (most recent call last):
  File "/mnt/Storage/home/wangjin/miniconda3/miniconda3/envs/py3.5/bin//pvacseq", line 11, in <module>
    sys.exit(main())
  File "/mnt/Storage/home/wangjin/miniconda3/miniconda3/envs/py3.5/lib/python3.5/site-packages/tools/pvacseq/main.py", line 92, in main
    args[0].func.main(args[1])
  File "/mnt/Storage/home/wangjin/miniconda3/miniconda3/envs/py3.5/lib/python3.5/site-packages/tools/pvacseq/run.py", line 82, in main
    lib.call_iedb.setup_iedb_conda_env()
  File "/mnt/Storage/home/wangjin/miniconda3/miniconda3/envs/py3.5/lib/python3.5/site-packages/lib/call_iedb.py", line 13, in setup_iedb_conda_env
    version_check = run("/bin/bash -l -c \" conda activate pvactools_py27 && python -c \\\"import platform; print(platform.python_version())\\\"\"", stdout=PIPE, check=True, shell=True)
  File "/mnt/Storage/home/wangjin/miniconda3/miniconda3/envs/py3.5/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '/bin/bash -l -c " conda activate pvactools_py27 && python -c \"import platform; print(platform.python_version())\""' returned non-zero exit status 1

**Here is the conda information, pvacseq information and server information:**

1. conda:
    active environment : base
    shell level : 1
    conda version : 4.7.12
    conda-build version : not installed
    python version : 3.7.4.final.0
    platform : linux-64
    user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Linux/4.4.0-62-generic ubuntu/16.04.2 glibc/2.23
    UID:GID : 1023:1001
    netrc file : None
    offline mode : False

2. pvactools:
    version: 1.5.3

3. ubuntu server:
    Ubuntu 16.04.2 LTS \n \l
    Linux BioServer1 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

4. ~/.bashrc content

__conda_setup="$('/mnt/Storage/home/wangjin/miniconda3/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/mnt/Storage/home/wangjin/miniconda3/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/mnt/Storage/home/wangjin/miniconda3/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/mnt/Storage/home/wangjin/miniconda3/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup

###my test on pvacseq
export -f conda
export -f __conda_activate
export -f __conda_reactivate
export -f __conda_hashr

**Comment by susannasiebert** [comment] 2019-12-02 14:58
This is a duplicate of issue https://github.com/griffithlab/pVACtools/issues/396.  You should be able to fix it by following the instructions [here](https://github.com/conda/conda/blob/master/CHANGELOG.md#440-2017-12-20).

**Comment by serge2016** [comment] 2019-12-02 15:05
@pfren1998, if you don't want to use conda, take a look at https://github.com/griffithlab/pVACtools/issues/357#issuecomment-481714768

**Comment by pfren1998** [comment] 2019-12-05 08:19
@susannasiebert, Thanks for your advice, I  have tried to add source path/conda.sh into .bashrc and also my snakemake srcipts, but it doesn't work.
@serge2016, Thanks for your advice, but I am working on a pipeline, most of the users are not experienced with linux, I want to make sure that the pipeline is as easy as possible

**Comment by susannasiebert** [comment] 2019-12-05 14:19
Could you please post the contents of your updated .bashrc file again?

Unfortunately, we really aren't able to help much with the system-specific installation issues. We generally recommend that users switch to using our docker images to get around these sort of issues.

**Comment by pfren1998** [comment] 2019-12-09 04:05
```shell
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/mnt/Storage/home/wangjin/miniconda3/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/mnt/Storage/home/wangjin/miniconda3/miniconda3/etc/profile.d/conda.sh" ]; then
 . "/mnt/Storage/home/wangjin/miniconda3/miniconda3/etc/profile.d/conda.sh" 
    else
 export PATH="/mnt/Storage/home/wangjin/miniconda3/miniconda3/bin:$PATH"  
    fi
fi
unset __conda_setup

###my test on pvacseq
export -f conda
export -f __conda_activate
export -f __conda_reactivate
export -f __conda_hashr
export -f __add_sys_prefix_to_path

. /mnt/Storage/home/wangjin/miniconda3/miniconda3/etc/profile.d/conda.sh
conda activate base
```

**Comment by pfren1998** [comment] 2019-12-09 06:37
**Here is my .bashrc content**
```shell
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/mnt/Storage/home/wangjin/miniconda3/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/mnt/Storage/home/wangjin/miniconda3/miniconda3/etc/profile.d/conda.sh" ]; then
 . "/mnt/Storage/home/wangjin/miniconda3/miniconda3/etc/profile.d/conda.sh" 
    else
 export PATH="/mnt/Storage/home/wangjin/miniconda3/miniconda3/bin:$PATH"  
    fi
fi
unset __conda_setup

#source conda.sh
. /mnt/Storage/home/wangjin/miniconda3/miniconda3/etc/profile.d/conda.sh
conda activate base
```
I will have a try with docker! Thanks!

**Comment by susannasiebert** [comment] 2020-02-25 20:31
Closing since there hasn't been any more activity on this ticket.

**Closed by susannasiebert** 2020-02-25 20:31 UTC
