### ISSUE TITLE
[Bug report title]NoneType Error Encountered with NetMHCpan and Exception When Calling MHCflurry

### ISSUE THREAD

**Issue by anomibo** [griffithlab/pVACtools#1154] opened 2024-09-27 12:24 UTC
### Installation Type

Docker

### pVACtools Version / Docker Image

griffithlab/pvactools:4.4.1

### Describe the bug

Hello! After pulling the latest version of the Docker image, I followed the pVACtools 4.4.1 documentation to test with the example data. When the algorithm was specified as 'all', I encountered this error.

_During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pvactools/tools/pvacseq/main.py", line 130, in main
    args[0].func.main(args[1])
  File "/usr/local/lib/python3.7/site-packages/pvactools/tools/pvacseq/run.py", line 142, in main
    pipeline.execute()
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/pipeline.py", line 451, in execute
    self.call_iedb(chunks)
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/pipeline.py", line 358, in call_iedb
    p.print("Making binding predictions on Allele %s and Epitope Length %s with Method %s - File %s - Completed" % (a, epl, method, filename))
  File "/usr/local/lib/python3.7/site-packages/pymp/__init__.py", line 148, in __exit__
    raise exc_t(exc_val)
Exception: An error occurred while calling MHCflurry:_

After adjusting the command and specifying the algorithm as NetMHCpan, I encountered this error.

_Making binding predictions on Allele HLA-A*29:02 and Epitope Length 10 with Method NetMHCpan - File /pvacseq_output_data/MHC_Class_I/tmp/HCC1395_TUMOR_DNA.netmhcpan.HLA-A*29:02.10.tsv_1201-1400
Illegal instruction
2024-09-27:12:01:18,780 WARNING  [__init__.py:662] did not find allele distance info from netmhcpan_output
An exception occured in thread 0: (<class 'TypeError'>, a bytes-like object is required, not 'NoneType').
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/pipeline.py", line 357, in call_iedb
    pvactools.lib.call_iedb.main(arguments)
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/call_iedb.py", line 53, in main
    tmp_output_filehandle.write(response_text)
TypeError: a bytes-like object is required, not 'NoneType'_

_During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pvactools/tools/pvacseq/main.py", line 130, in main
    args[0].func.main(args[1])
  File "/usr/local/lib/python3.7/site-packages/pvactools/tools/pvacseq/run.py", line 142, in main
    pipeline.execute()
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/pipeline.py", line 451, in execute
    self.call_iedb(chunks)
  File "/usr/local/lib/python3.7/site-packages/pvactools/lib/pipeline.py", line 358, in call_iedb
    p.print("Making binding predictions on Allele %s and Epitope Length %s with Method %s - File %s - Completed" % (a, epl, method, filename))
  File "/usr/local/lib/python3.7/site-packages/pymp/__init__.py", line 148, in __exit__
    raise exc_t(exc_val)
TypeError: a bytes-like object is required, not 'NoneType'_

### How to reproduce this bug

```Shell
docker run --rm -v /Users/anomibo/Downloads/pvactools/example_data/pvacseq_example_data:/pvacseq_example_data -v /Users/anomibo/Downloads/pvactools/output:/pvacseq_output_data -it griffithlab/pvactools

pvacseq run \
> /pvacseq_example_data/annotated.expression.vcf.gz \
> HCC1395_TUMOR_DNA \
> HLA-A*29:02,HLA-B*45:01,DRB1*04:05 \
> all \
> /pvacseq_output_data \
> -e1 8,9,10 \
> -e2 15 \
> --normal-sample-name HCC1395_NORMAL_DNA \
> --iedb-install-directory /opt/iedb
```

### Input files

pvacseq_example_data

### Log output

 I did not receive the expected TSV file. Here are the complete results, including the log file. Thank you in advance for your response.

[MHC_Class_I.zip](https://github.com/user-attachments/files/17164075/MHC_Class_I.zip)

**Comment by susannasiebert** [comment] 2024-10-03 13:31
Unfortunately, I'm unable to reproduce this error. Would you be able to attach the full pVACseq stdout/stderr output for your runs?

We sometimes see similar errors if the machine doesn't have enough memory or tmp space available (usually memory). What are the specs on your machine?

**Comment by anomibo** [comment] 2024-10-10 05:10
Thank you very much for your response. I was originally working on a MacOS machine with 16GB of RAM. After attempting deployment on a Linux server using conda, I found that all algorithms except for NetMHCcons are running as expected. I suspect that the issues might be related to docker and NetMHCcons. Although the specific problems have not been resolved, the results obtained from using alternative algorithms are sufficient for my experimental needs. I apologize for any inconvenience, and I hope you have a wonderful day.



&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, Oct 3, 2024 09:32 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [griffithlab/pVACtools] [Bug report title]NoneType Error Encountered with NetMHCpan and Exception When Calling MHCflurry (Issue #1154)

&nbsp;



 
Unfortunately, I'm unable to reproduce this error. Would you be able to attach the full pVACseq stdout/stderr output for your runs?
 
We sometimes see similar errors if the machine doesn't have enough memory or tmp space available (usually memory). What are the specs on your machine?

**Comment by susannasiebert** [comment] 2024-10-10 13:53
Glad you were able to get it to work (for the most part). NetMHCcon is one of those algorithms that needs even more memory than the rest because it calls 3 (I believe) algorithms underneath the hood to find a consensus score. For reference, we use 32Gb in our workflows. I'm closing this issue since your immediate problem is resolved.

**Closed by susannasiebert** 2024-10-10 13:53 UTC
Labels: bug report / hotfix PR
