### ISSUE TITLE
File "/usr/local/lib/python3.5/site-packages/pvactools-1.3.7-py3.5.egg/lib/output_parser.py", line 505, in parse_iedb_file     if protein_identifiers_from_label[protein_label] is not None: KeyError: 65

### ISSUE THREAD

**Issue by qindan2008** [griffithlab/pVACtools#387] opened 2019-05-08 03:58 UTC
* pvactools version: 1.3.7
* Python version: python3.5 -V returns Python 3.5.6, python -V returns Python 2.7.15+
* Operating System: ubuntu 14.04

**Describe the bug**

When I test the pvactools pipeline with its build-in test data "test_data/pvacseq/input.vcf", the pipeline could finish successfully. But when I use my own data, error occurred. 

/usr/local/lib/python3.5/site-packages/pvactools-1.3.7-py3.5.egg/lib/output_parser.py:485: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  protein_identifiers_from_label = yaml.load(key_file_reader)

My input somatic vcf file is first generated by strelka2 variant caller, and then processed to  feed into  pvactools.

**To Reproduce**
```
pvacseq run \
/DataProcess/Project/neoepiscope/pvacseq/Tumor_Normal.strelka2.somatic.vep.pavseqinput.vcf  \
Tumor  \
 HLA-A*11:01,HLA-A*02:01,HLA-B*55:01,HLA-B*13:01,HLA-C*01:02,HLA-C*03:04  \
 NNalign NetMHC PickPocket SMM SMMPMBEC SMMalign  \
 ./Tumor_Normal \
 -e 8,9,10   -t  15  --normal-sample-name  Normal
```
**Log Output**
```
The standard output showed that "Parsing prediction file for Allele HLA-x*xx:xx and Epitope Length x - Entries x-xx - Completed", and then errors occurred:

/usr/local/lib/python3.5/site-packages/pvactools-1.3.7-py3.5.egg/lib/output_parser.py:485: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  protein_identifiers_from_label = yaml.load(key_file_reader)
Traceback (most recent call last):
  File "/usr/local/bin/pvacseq", line 11, in <module>
    load_entry_point('pvactools==1.3.7', 'console_scripts', 'pvacseq')()
  File "/usr/local/lib/python3.5/site-packages/pvactools-1.3.7-py3.5.egg/tools/pvacseq/main.py", line 92, in main
    args[0].func.main(args[1])
  File "/usr/local/lib/python3.5/site-packages/pvactools-1.3.7-py3.5.egg/tools/pvacseq/run.py", line 163, in main
    pipeline.execute()
  File "/usr/local/lib/python3.5/site-packages/pvactools-1.3.7-py3.5.egg/lib/pipeline.py", line 427, in execute
    split_parsed_output_files = self.parse_outputs(chunks)
  File "/usr/local/lib/python3.5/site-packages/pvactools-1.3.7-py3.5.egg/lib/pipeline.py", line 388, in parse_outputs
    parser.execute()
  File "/usr/local/lib/python3.5/site-packages/pvactools-1.3.7-py3.5.egg/lib/output_parser.py", line 384, in execute
    iedb_results = self.process_input_iedb_file(tsv_entries)
  File "/usr/local/lib/python3.5/site-packages/pvactools-1.3.7-py3.5.egg/lib/output_parser.py", line 317, in process_input_iedb_file
    iedb_results = self.parse_iedb_file(tsv_entries)
  File "/usr/local/lib/python3.5/site-packages/pvactools-1.3.7-py3.5.egg/lib/output_parser.py", line 505, in parse_iedb_file
    if protein_identifiers_from_label[protein_label] is not None:
KeyError: 65

```

**Output File**
Tumor_Normal/MHC_Class_I/tmp
Tumor_Normal/MHC_Class_I/log
Tumor_Normal/MHC_Class_I/Tumor.tsv
Many Tumor_Normal/MHC_Class_I/Tumor.tsv_xxx-yyy files.

**Expected behavior**
My input somatic vcf is here:
[input_vcf.zip](https://github.com/griffithlab/pVACtools/files/3155429/input_vcf.zip)

**Comment by susannasiebert** [comment] 2019-05-09 16:54
Unfortunately, I was unable to reproduce this error. Can you try rerunning with an empty output directory?

**Comment by susannasiebert** [comment] 2019-05-30 13:56
Since there is no more activity on this ticket I assume that the problem was resolved by running with an empty output directory. I'm closing this ticket but please do reopen if you're still running into this error.

**Closed by susannasiebert** 2019-05-30 13:56 UTC

**Comment by bioxu** [comment] 2022-07-08 04:16
I am having the same issue in some times, but rerun successfully.  Maybe it is a bug.

pvactools version: newest docker
Python version: 2.7
Operating System: ubuntu

**Comment by susannasiebert** [comment] 2022-07-08 13:50
Would you be able to provide me with the output files from one of the failed runs that has this error (before you reran it)?
