### ISSUE TITLE
pVACseq TypeError in top score filter

### ISSUE THREAD

**Issue by rbowenj** [griffithlab/pVACtools#683] opened 2021-07-13 01:11 UTC
Hi,

I'm encountering the following error when running pVACseq (using Docker `griffithlab/pvactools:2.0.2`):
```
Traceback (most recent call last):
  File "/usr/local/bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/tools/pvacseq/main.py", line 95, in main
    args[0].func.main(args[1])
  File "/usr/local/lib/python3.7/site-packages/tools/pvacseq/run.py", line 122, in main
    pipeline.execute()
  File "/usr/local/lib/python3.7/site-packages/lib/pipeline.py", line 504, in execute
    PostProcessor(**post_processing_params).execute()
  File "/usr/local/lib/python3.7/site-packages/lib/post_processor.py", line 34, in execute
    self.execute_top_score_filter()
  File "/usr/local/lib/python3.7/site-packages/lib/post_processor.py", line 102, in execute_top_score_filter
    TopScoreFilter(self.transcript_support_level_filter_fh.name, self.top_score_filter_fh.name, self.top_score_metric, 
  self.file_type).execute()
    File "/usr/local/lib/python3.7/site-packages/lib/top_score_filter.py", line 98, in execute
  line_with_lowest_transcript_id = self.find_line_with_lowest_transcript_id(lines)
    File "/usr/local/lib/python3.7/site-packages/lib/top_score_filter.py", line 25, in find_line_with_lowest_transcript_id
  if transcript_id < lowest_transcript_id:
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```
This results in no filtered TSV being created.
Do you have any recommendations on how to fix this?

Thanks!

**Comment by susannasiebert** [comment] 2021-07-13 14:00
Thank you for this bug report. This seems to be a problem with the transcript IDs in the VEP annotations of your VCF. Would you be able to share your all_epitopes file with us?

**Comment by rbowenj** [comment] 2021-07-15 05:18
Thanks for your quick response! This is the all_epitopes file: 
[all_epitopes.txt](https://github.com/griffithlab/pVACtools/files/6820403/all_epitopes.txt)

**Comment by susannasiebert** [comment] 2021-07-16 16:38
I determined the cause of your errors. It is a bug with our top score filter code which currently doesn't support transcripts starting with `NM_`. I added support for this case in pull request #685 and I will need to make a new hotfix release once this issue is merged. I expect to make that release sometime next week.

**Comment by susannasiebert** [comment] 2021-08-03 15:37
I apologize for this delay but a new version of pVACtools (2.0.3) is now available which should fix this problem. Please let me know if you continue to encounter any errors.

**Closed** 2021-08-03 15:37 UTC
