### ISSUE TITLE
Traceback (most recent call last): change_permissions_recursive

### ISSUE THREAD

**Issue by xmy1990** [griffithlab/pVACtools#1085] opened 2024-03-21 07:51 UTC
Hi,
Previously, I had success using pvactools on Ubuntu ,  but this time I encountered the following error:

Traceback (most recent call last):
  File "bin/pvacseq", line 8, in <module>
    sys.exit(main())
  File "lib/python3.7/site-packages/pvactools/tools/pvacseq/main.py", line 116, in main
    args[0].func.main(args[1])
  File "lib/python3.7/site-packages/pvactools/tools/pvacseq/run.py", line 170, in main
    pvactools.lib.run_utils.change_permissions_recursive(base_output_dir, 0o755, 0o644)
  File "lib/python3.7/site-packages/pvactools/lib/run_utils.py", line 96, in change_permissions_recursive
    os.chmod(file, file_mode)

Thanks!

**Comment by xmy1990** [comment] 2024-03-21 08:30
The result seems fine, but there is an  above error in the process.
Thanks!

**Comment by susannasiebert** [comment] 2024-03-21 15:15
Thank you for this bug report. Can you please attach the full stack trace for this error? Unfortunately, the original stderr you posted doesn't include the actual error message. 

Additionally, can you please post the pVACtools command you ran?

**Comment by xmy1990** [comment] 2024-03-21 15:30
I just get the above errors.
The other original stderr had no errors, it was all ok.
The result  was also seemed ok.

Thanks

**Comment by susannasiebert** [comment] 2024-03-21 15:39
That is weird because it doesn't actually mention a specific error message, just the lines of the files it executed when it ran into the problem. What does the stdout say? 

Again, can you please attach the command you tried to run? Are there specific steps that can be taken to replicate this issue consistently? 

Without a specific error message or steps to reproduce this issue on my end there isn't much I can do to fix this.

**Comment by xmy1990** [comment] 2024-03-21 16:06
pVACtools command ：
pvacseq run \
$input_vcf \
$tumor_name \
$hla_type \
MHCflurry \
$tmp \
-e1 8,9,10,11 \
--normal-sample-name $normal_name \
--iedb-install-directory $iedb_dir \
--blastp-path $blastp_path \
-b $ic50 \
--percentile-threshold $rank_p \
-m median \
--normal-cov $normal_cov \
--normal-vaf $normal_vaf \
--tdna-cov $tumor_cov \
--tdna-vaf $tumor_vaf \
-t $number_threads

Thanks！

**Comment by susannasiebert** [comment] 2024-03-21 17:32
Was this run under docker or a standalone installation?

**Comment by xmy1990** [comment] 2024-03-22 01:09
standalone installation

**Comment by susannasiebert** [comment] 2024-03-22 14:46
Unfortunately, I'm unable to replicate this issue on my end. If you can provide a set of steps to reliably replicate this issue, I'm happy to investigate further. Otherwise I will have to close this issue.

**Comment by susannasiebert** [comment] 2024-05-31 15:23
Closing this issue due to inactivity.

**Closed by susannasiebert** 2024-05-31 15:23 UTC
