### ISSUE TITLE
pVACtools and IEDB installation (https://pvactools.readthedocs.io/en/latest/install.html)

### ISSUE THREAD

**Issue by ArisStefanosSn** [griffithlab/pVACtools#840] opened 2022-09-07 18:26 UTC
* pvactools version: 3.0.3
* Python version: 3
* Operating System: Mac OS (Monterey version 12.5.1)

Dear developers, I am following the instructions of https://pvactools.readthedocs.io/en/latest/install.html to install pVACtools in my system (with some necessary modifications shown below). I installed successfully pvactools with conda:

> conda create -n pVACtools python=3.6
> source activate pVACtools
> pip install pvactools==1.2.0

and installed the tensorflow as suggested in other Github issues (https://github.com/griffithlab/pVACtools/issues/314):

> conda install tensorflow==1.8 

Then I upgraded pvactools (also suggested in the above link):

> pip install pvactools --upgrade

 This is the output showing successful installation:

> pvacseq run -v

> usage: pvacseq run [-h] [-e1 CLASS_I_EPITOPE_LENGTH]
>                    [-e2 CLASS_II_EPITOPE_LENGTH]
>                    [--iedb-install-directory IEDB_INSTALL_DIRECTORY]
>                    [-b BINDING_THRESHOLD]
>                    [--percentile-threshold PERCENTILE_THRESHOLD]
>                    [--allele-specific-binding-thresholds] [-m {lowest,median}]
>                    [-r IEDB_RETRIES] [-k] [-t N_THREADS]
>                    [--net-chop-method {cterm,20s}] [--netmhc-stab]
>                    [--net-chop-threshold NET_CHOP_THRESHOLD]
>                    [--run-reference-proteome-similarity]
>                    [--blastp-path BLASTP_PATH]
>                    [--blastp-db {refseq_select_prot,refseq_protein}]
>                    [-a {sample_name}] [-s FASTA_SIZE] [--exclude-NAs]
>                    [-d DOWNSTREAM_SEQUENCE_LENGTH]
>                    [--normal-sample-name NORMAL_SAMPLE_NAME]
>                    [-p PHASED_PROXIMAL_VARIANTS_VCF] [-c MINIMUM_FOLD_CHANGE]
>                    [--normal-cov NORMAL_COV] [--tdna-cov TDNA_COV]
>                    [--trna-cov TRNA_COV] [--normal-vaf NORMAL_VAF]
>                    [--tdna-vaf TDNA_VAF] [--trna-vaf TRNA_VAF]
>                    [--expn-val EXPN_VAL]
>                    [--maximum-transcript-support-level {1,2,3,4,5}]
>                    [--pass-only] [--tumor-purity TUMOR_PURITY]
>                    input_file sample_name allele
>                    {MHCflurry,MHCnuggetsI,MHCnuggetsII,NNalign,NetMHC,NetMHCIIpan,NetMHCcons,NetMHCpan,PickPocket,SMM,SMMPMBEC,SMMalign,all,all_class_i,all_class_ii}
>                    [{MHCflurry,MHCnuggetsI,MHCnuggetsII,NNalign,NetMHC,NetMHCIIpan,NetMHCcons,NetMHCpan,PickPocket,SMM,SMMPMBEC,SMMalign,all,all_class_i,all_class_ii} ...]
>                    output_dir
> pvacseq run: error: the following arguments are required: input_file, sample_name, allele, prediction_algorithms, output_dir

 
To install the MHC Class I I installed gawk and wget from homebrew and ran:

> wget https://downloads.iedb.org/tools/mhci/3.1.2/IEDB_MHC_I-3.1.2.tar.gz
> tar -zxvf IEDB_MHC_I-3.1.2.tar.gz
> cd mhc_i
> ./configure 

This was also successful.

I have issues to install MHC Class II (in the same way):

> wget https://downloads.iedb.org/tools/mhcii/3.1.6/IEDB_MHC_II-3.1.6.tar.gz
> tar -zxvf IEDB_MHC_II-3.1.6.tar.gz
> cd mhc_ii
> ./configure.py

I see the configure.py in the mhc_ii folder but when running the last line I got the error:

> ./configure.py: /usr/bin/python: bad interpreter: No such file or directory 

I figured that the problem was in calling python (I have python3) and I called (or added in ~/.bashrc):

> alias python=python3

which have me:

> python --version
> Python 3.10.6
> python3 --version
> Python 3.10.6

Trying ./configure.py gave me again the above error. I edited the configure.py (first line) as:

> #! /usr/bin/python3 

and rerun the ./configure.py to get:

> ./configure.py
> All prerequisites found!
> run MHCII tests...
> /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py:946: ResourceWarning: subprocess 89192 is still running
>   _warn("subprocess %s is still running" % self.pid,
> ResourceWarning: Enable tracemalloc to get the object allocation traceback
> ./configure.py:28: ResourceWarning: unclosed file <_io.TextIOWrapper name=3 encoding='UTF-8'>
>   result=os.popen(cmd).read()
> ResourceWarning: Enable tracemalloc to get the object allocation traceback
> ./Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py:946: ResourceWarning: subprocess 89225 is still running
>   _warn("subprocess %s is still running" % self.pid,
> ResourceWarning: Enable tracemalloc to get the object allocation traceback
> list index out of range
> ./configure.py:18: ResourceWarning: unclosed file <_io.TextIOWrapper name=3 encoding='UTF-8'>
>   result=os.popen(cmd).read()
> ResourceWarning: Enable tracemalloc to get the object allocation traceback
> F./Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py:946: ResourceWarning: subprocess 89262 is still running
>   _warn("subprocess %s is still running" % self.pid,
> ResourceWarning: Enable tracemalloc to get the object allocation traceback
> sh: /Users/motake/Documents/Work/PVACTools/mhc_ii/methods/netmhciipan-4.0-executable/netmhciipan_4_0_executable/Darwin_x86_64/bin/nnalign_gaps_pan_play_MA_wgt_MN_v2_two_outputs_context_allelelist_pboth: No such file or directory
> ./configure.py:33: ResourceWarning: unclosed file <_io.TextIOWrapper name=3 encoding='UTF-8'>
>   result=os.popen(cmd).read()
> ResourceWarning: Enable tracemalloc to get the object allocation traceback
> F/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py:946: ResourceWarning: subprocess 89308 is still running
>   _warn("subprocess %s is still running" % self.pid,
> ResourceWarning: Enable tracemalloc to get the object allocation traceback
> ./configure.py:38: ResourceWarning: unclosed file <_io.TextIOWrapper name=3 encoding='UTF-8'>
>   result=os.popen(cmd).read()
> ResourceWarning: Enable tracemalloc to get the object allocation traceback
> F/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py:946: ResourceWarning: subprocess 89347 is still running
>   _warn("subprocess %s is still running" % self.pid,
> ResourceWarning: Enable tracemalloc to get the object allocation traceback
> ./configure.py:13: ResourceWarning: unclosed file <_io.TextIOWrapper name=3 encoding='UTF-8'>
>   result=os.popen('echo example').read()
> ResourceWarning: Enable tracemalloc to get the object allocation traceback
> ./Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py:946: ResourceWarning: subprocess 89348 is still running
>   _warn("subprocess %s is still running" % self.pid,
> ResourceWarning: Enable tracemalloc to get the object allocation traceback
> list index out of range
> ./configure.py:23: ResourceWarning: unclosed file <_io.TextIOWrapper name=3 encoding='UTF-8'>
>   result=os.popen(cmd).read()
> ResourceWarning: Enable tracemalloc to get the object allocation traceback
> F/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py:946: ResourceWarning: subprocess 89388 is still running
>   _warn("subprocess %s is still running" % self.pid,
> ResourceWarning: Enable tracemalloc to get the object allocation traceback
> list index out of range
> ./configure.py:43: ResourceWarning: unclosed file <_io.TextIOWrapper name=3 encoding='UTF-8'>
>   result=os.popen(cmd).read()
> ResourceWarning: Enable tracemalloc to get the object allocation traceback
> F/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py:946: ResourceWarning: subprocess 89427 is still running
>   _warn("subprocess %s is still running" % self.pid,
> ResourceWarning: Enable tracemalloc to get the object allocation traceback
> ./configure.py:48: ResourceWarning: unclosed file <_io.TextIOWrapper name=3 encoding='UTF-8'>
>   result=os.popen(cmd).read()
> ResourceWarning: Enable tracemalloc to get the object allocation traceback
> .
> ======================================================================
> FAIL: test_consensus (__main__.Test_test)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "./configure.py", line 19, in test_consensus
>     self.assertEqual(result, 'allele\tseq_num\tstart\tend\tlength\tpeptide\tconsensus_percentile_rank\tadjusted_consensus_percentile_rank\tcomblib_core\tcomblib_score\tcomblib_rank\tadjusted_comblib_rank\tsmm_align_core\tsmm_align_ic50\tsmm_align_rank\tadjusted_smm_align_rank\tnn_align_core\tnn_align_ic50\tnn_align_rank\tadjusted_nn_align_rank\tsturniolo_core\tsturniolo_score\tsturniolo_rank\tadjusted_sturniolo_rank\nHLA-DRB1*03:01\t1\t8\t22\t15\tEGVSGATWVDLVLEG\t59.0\t59.00\t-\t-\t-\t-\tVSGATWVDL\t5932.0\t59.0\t59.00\tTWVDLVLEG\t3356.9\t50.0\t50.00\tVSGATWVDL\t-1.34\t88.0\t88.00\nHLA-DRB1*03:01\t1\t4\t18\t15\tRDFLEGVSGATWVDL\t85.0\t85.00\t-\t-\t-\t-\tFLEGVSGAT\t8523.0\t69.0\t69.00\tVSGATWVDL\t12707.7\t85.0\t85.00\tFLEGVSGAT\t-1.2\t87.0\t87.00\nHLA-DRB1*03:01\t1\t5\t19\t15\tDFLEGVSGATWVDLV\t85.0\t85.00\t-\t-\t-\t-\tFLEGVSGAT\t18841.0\t85.0\t85.00\tVSGATWVDL\t10634.4\t81.0\t81.00\tFLEGVSGAT\t-1.2\t87.0\t87.00\nHLA-DRB1*03:01\t1\t6\t20\t15\tFLEGVSGATWVDLVL\t85.0\t85.00\t-\t-\t-\t-\tFLEGVSGAT\t18363.0\t85.0\t85.00\tVSGATWVDL\t8154.8\t74.0\t74.00\tFLEGVSGAT\t-1.2\t87.0\t87.00\nHLA-DRB1*03:01\t1\t1\t15\t15\tMSNRDFLEGVSGATW\t87.0\t87.00\t-\t-\t-\t-\tFLEGVSGAT\t9343.0\t71.0\t71.00\tDFLEGVSGA\t17372.9\t92.0\t92.00\tFLEGVSGAT\t-1.2\t87.0\t87.00\nHLA-DRB1*03:01\t1\t2\t16\t15\tSNRDFLEGVSGATWV\t87.0\t87.00\t-\t-\t-\t-\tFLEGVSGAT\t8986.0\t70.0\t70.00\tDFLEGVSGA\t18531.9\t93.0\t93.00\tFLEGVSGAT\t-1.2\t87.0\t87.00\nHLA-DRB1*03:01\t1\t3\t17\t15\tNRDFLEGVSGATWVD\t87.0\t87.00\t-\t-\t-\t-\tFLEGVSGAT\t9085.0\t70.0\t70.00\tDFLEGVSGA\t18458.2\t93.0\t93.00\tFLEGVSGAT\t-1.2\t87.0\t87.00\nHLA-DRB1*03:01\t1\t7\t21\t15\tLEGVSGATWVDLVLE\t88.0\t88.00\t-\t-\t-\t-\tSGATWVDLV\t26621.0\t91.0\t91.00\tVSGATWVDL\t5473.3\t63.0\t63.00\tVSGATWVDL\t-1.34\t88.0\t88.00\n')
> AssertionError: 'netMHCII: no binaries found for Darwin_x86_64\n' != 'allele\tseq_num\tstart\tend\tlength\tpept[1684 chars]00\n'
> Diff is 1580 characters long. Set self.maxDiff to None to see it.
> 
> ======================================================================
> FAIL: test_netmhciipan (__main__.Test_test)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "./configure.py", line 34, in test_netmhciipan
>     self.assertEqual(result, 'allele\tseq_num\tstart\tend\tlength\tcore_peptide\tpeptide\tic50\tpercentile_rank\tadjusted_rank\nHLA-DRB1*03:01\t1\t8\t22\t15\tTWVDLVLEG\tEGVSGATWVDLVLEG\t6159.57\t71.0\t71.00\nHLA-DRB1*03:01\t1\t6\t20\t15\tGATWVDLVL\tFLEGVSGATWVDLVL\t9173.76\t84.0\t84.00\nHLA-DRB1*03:01\t1\t7\t21\t15\tGATWVDLVL\tLEGVSGATWVDLVLE\t9199.80\t84.0\t84.00\nHLA-DRB1*03:01\t1\t1\t15\t15\tSNRDFLEGV\tMSNRDFLEGVSGATW\t9532.78\t85.0\t85.00\nHLA-DRB1*03:01\t1\t4\t18\t15\tLEGVSGATW\tRDFLEGVSGATWVDL\t10018.37\t86.0\t86.00\nHLA-DRB1*03:01\t1\t5\t19\t15\tLEGVSGATW\tDFLEGVSGATWVDLV\t10379.28\t87.0\t87.00\nHLA-DRB1*03:01\t1\t2\t16\t15\tLEGVSGATW\tSNRDFLEGVSGATWV\t10436.49\t87.0\t87.00\nHLA-DRB1*03:01\t1\t3\t17\t15\tLEGVSGATW\tNRDFLEGVSGATWVD\t11966.01\t91.0\t91.00\n'  )
> AssertionError: 'alle[89 chars]ank\n' != 'alle[89 chars]ank\nHLA-DRB1*03:01\t1\t8\t22\t15\tTWVDLVLEG\t[599 chars]00\n'
> Diff is 671 characters long. Set self.maxDiff to None to see it.
> 
> ======================================================================
> FAIL: test_nn (__main__.Test_test)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "./configure.py", line 39, in test_nn
>     self.assertEqual(result, 'allele\tseq_num\tstart\tend\tlength\tcore_peptide\tpeptide\tic50\tpercentile_rank\tadjusted_rank\nHLA-DRB1*03:01\t1\t8\t22\t15\tTWVDLVLEG\tEGVSGATWVDLVLEG\t3356.90\t50.0\t50.00\nHLA-DRB1*03:01\t1\t7\t21\t15\tVSGATWVDL\tLEGVSGATWVDLVLE\t5473.30\t63.0\t63.00\nHLA-DRB1*03:01\t1\t6\t20\t15\tVSGATWVDL\tFLEGVSGATWVDLVL\t8154.80\t74.0\t74.00\nHLA-DRB1*03:01\t1\t5\t19\t15\tVSGATWVDL\tDFLEGVSGATWVDLV\t10634.40\t81.0\t81.00\nHLA-DRB1*03:01\t1\t4\t18\t15\tVSGATWVDL\tRDFLEGVSGATWVDL\t12707.70\t85.0\t85.00\nHLA-DRB1*03:01\t1\t1\t15\t15\tDFLEGVSGA\tMSNRDFLEGVSGATW\t17372.90\t92.0\t92.00\nHLA-DRB1*03:01\t1\t3\t17\t15\tDFLEGVSGA\tNRDFLEGVSGATWVD\t18458.20\t93.0\t93.00\nHLA-DRB1*03:01\t1\t2\t16\t15\tDFLEGVSGA\tSNRDFLEGVSGATWV\t18531.90\t93.0\t93.00\n')
> AssertionError: 'alle[89 chars]ank\n' != 'alle[89 chars]ank\nHLA-DRB1*03:01\t1\t8\t22\t15\tTWVDLVLEG\t[600 chars]00\n'
> Diff is 672 characters long. Set self.maxDiff to None to see it.
> 
> ======================================================================
> FAIL: test_recommended (__main__.Test_test)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "./configure.py", line 24, in test_recommended
>     self.assertEqual(result, 'allele\tseq_num\tstart\tend\tlength\tmethod\tpeptide\tconsensus_percentile_rank\tadjusted_consensus_percentile_rank\tcomblib_core\tcomblib_score\tcomblib_rank\tadjusted_comblib_rank\tsmm_align_core\tsmm_align_ic50\tsmm_align_rank\tadjusted_smm_align_rank\tnn_align_core\tnn_align_ic50\tnn_align_rank\tadjusted_nn_align_rank\tnetmhciipan_core\tnetmhciipan_ic50\tnetmhciipan_rank\tadjusted_netmhciipan_rank\tsturniolo_core\tsturniolo_score\tsturniolo_rank\tadjusted_sturniolo_rank\nHLA-DRB1*03:01\t1\t8\t22\t15\tSMM-NN-Sturniolo\tEGVSGATWVDLVLEG\t59.0\t59.00\t-\t-\t-\t-\tVSGATWVDL\t5932.0\t59.0\t59.00\tTWVDLVLEG\t3356.9\t50.0\t50.00\t-\t-\t-\t-\tVSGATWVDL\t-1.34\t88.0\t88.00\nHLA-DRB1*03:01\t1\t4\t18\t15\tSMM-NN-Sturniolo\tRDFLEGVSGATWVDL\t85.0\t85.00\t-\t-\t-\t-\tFLEGVSGAT\t8523.0\t69.0\t69.00\tVSGATWVDL\t12707.7\t85.0\t85.00\t-\t-\t-\t-\tFLEGVSGAT\t-1.2\t87.0\t87.00\nHLA-DRB1*03:01\t1\t5\t19\t15\tSMM-NN-Sturniolo\tDFLEGVSGATWVDLV\t85.0\t85.00\t-\t-\t-\t-\tFLEGVSGAT\t18841.0\t85.0\t85.00\tVSGATWVDL\t10634.4\t81.0\t81.00\t-\t-\t-\t-\tFLEGVSGAT\t-1.2\t87.0\t87.00\nHLA-DRB1*03:01\t1\t6\t20\t15\tSMM-NN-Sturniolo\tFLEGVSGATWVDLVL\t85.0\t85.00\t-\t-\t-\t-\tFLEGVSGAT\t18363.0\t85.0\t85.00\tVSGATWVDL\t8154.8\t74.0\t74.00\t-\t-\t-\t-\tFLEGVSGAT\t-1.2\t87.0\t87.00\nHLA-DRB1*03:01\t1\t1\t15\t15\tSMM-NN-Sturniolo\tMSNRDFLEGVSGATW\t87.0\t87.00\t-\t-\t-\t-\tFLEGVSGAT\t9343.0\t71.0\t71.00\tDFLEGVSGA\t17372.9\t92.0\t92.00\t-\t-\t-\t-\tFLEGVSGAT\t-1.2\t87.0\t87.00\nHLA-DRB1*03:01\t1\t2\t16\t15\tSMM-NN-Sturniolo\tSNRDFLEGVSGATWV\t87.0\t87.00\t-\t-\t-\t-\tFLEGVSGAT\t8986.0\t70.0\t70.00\tDFLEGVSGA\t18531.9\t93.0\t93.00\t-\t-\t-\t-\tFLEGVSGAT\t-1.2\t87.0\t87.00\nHLA-DRB1*03:01\t1\t3\t17\t15\tSMM-NN-Sturniolo\tNRDFLEGVSGATWVD\t87.0\t87.00\t-\t-\t-\t-\tFLEGVSGAT\t9085.0\t70.0\t70.00\tDFLEGVSGA\t18458.2\t93.0\t93.00\t-\t-\t-\t-\tFLEGVSGAT\t-1.2\t87.0\t87.00\nHLA-DRB1*03:01\t1\t7\t21\t15\tSMM-NN-Sturniolo\tLEGVSGATWVDLVLE\t88.0\t88.00\t-\t-\t-\t-\tSGATWVDLV\t26621.0\t91.0\t91.00\tVSGATWVDL\t5473.3\t63.0\t63.00\t-\t-\t-\t-\tVSGATWVDL\t-1.34\t88.0\t88.00\n')
> AssertionError: 'netMHCII: no binaries found for Darwin_x86_64\n' != 'allele\tseq_num\tstart\tend\tlength\tmeth[2013 chars]00\n'
> Diff is 1864 characters long. Set self.maxDiff to None to see it.
> 
> ======================================================================
> FAIL: test_smm (__main__.Test_test)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "./configure.py", line 44, in test_smm
>     self.assertEqual(result, 'allele\tseq_num\tstart\tend\tlength\tcore_peptide\tpeptide\tic50\tpercentile_rank\tadjusted_rank\nHLA-DRB1*03:01\t1\t8\t22\t15\tVSGATWVDL\tEGVSGATWVDLVLEG\t5932.00\t59.0\t59.00\nHLA-DRB1*03:01\t1\t4\t18\t15\tFLEGVSGAT\tRDFLEGVSGATWVDL\t8523.00\t69.0\t69.00\nHLA-DRB1*03:01\t1\t2\t16\t15\tFLEGVSGAT\tSNRDFLEGVSGATWV\t8986.00\t70.0\t70.00\nHLA-DRB1*03:01\t1\t3\t17\t15\tFLEGVSGAT\tNRDFLEGVSGATWVD\t9085.00\t70.0\t70.00\nHLA-DRB1*03:01\t1\t1\t15\t15\tFLEGVSGAT\tMSNRDFLEGVSGATW\t9343.00\t71.0\t71.00\nHLA-DRB1*03:01\t1\t6\t20\t15\tFLEGVSGAT\tFLEGVSGATWVDLVL\t18363.00\t85.0\t85.00\nHLA-DRB1*03:01\t1\t5\t19\t15\tFLEGVSGAT\tDFLEGVSGATWVDLV\t18841.00\t85.0\t85.00\nHLA-DRB1*03:01\t1\t7\t21\t15\tSGATWVDLV\tLEGVSGATWVDLVLE\t26621.00\t91.0\t91.00\n')
> AssertionError: 'netMHCII: no binaries found for Darwin_x86_64\n' != 'allele\tseq_num\tstart\tend\tlength\tcore[696 chars]00\n'
> Diff is 718 characters long. Set self.maxDiff to None to see it.
> 
> ----------------------------------------------------------------------
> Ran 9 tests in 7.146s
> 
> FAILED (failures=5)

I am not sure what else I can do to fix this. It is strange that mhc_i installation was fine but in mhc_ii I had all these problems. Is it possible that some files from mhc_ii are missing (the architecture of the directories are not the same)?

Thank you,
Makis

**Comment by susannasiebert** [comment] 2022-09-07 19:06
Hi @ArisStefanosSn,

Thanks for you interest in pVACtools. I apologize that you're running into issues installing IEDB. From my recollection, the IEDB installation might've been successful, even if the tests fail. Have you tried running a test IEDB call to confirm? If the install doesn't work, I recommend putting in a ticket with IEDB directly (https://help.iedb.org/hc/en-us) as we are not affiliated with them and they will be able to better assist you with installation problems of their software.

We do provide IEDB installations as part of our docker images (the latest and latest-slim images) so that is an alternative as well.

Best,
Susanna

**Comment by ArisStefanosSn** [comment] 2022-09-13 14:39
Hi [@susannasiebert](https://github.com/susannasiebert),

Thank you for the previous response. I contacted the IEDB but I still encountered problems with the installation, so I decided to try (again) the Docker approach. I have singularity and I slightly modified the scripts at https://pvactools.readthedocs.io/en/latest/pvacseq/getting_started.html#pvacseq-docker (shouldn't be a problem). 

First I pulled the latest .sif:

> singularity pull docker://griffithlab/pvactools 

Then I followed the directions above (after downloading the example data) and ran the script:

> singularity run path/to/pvactools_latest.sif pvacseq run /path/to/input.vcf \
> Test \
> HLA-A*02:01,HLA-B*35:01,DRB1*11:01 \
> NNalign \
> /path/to/output/folder/

I see the error:

> No MHC class I prediction algorithms chosen. Skipping MHC class I predictions.
> Executing MHC Class II predictions
> Traceback (most recent call last):
>   File "/usr/local/bin/pvacseq", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.7/site-packages/pvactools/tools/pvacseq/main.py", line 116, in main
>     args[0].func.main(args[1])
>   File "/usr/local/lib/python3.7/site-packages/pvactools/tools/pvacseq/run.py", line 158, in main
>     pipeline.execute()
>   File "/usr/local/lib/python3.7/site-packages/pvactools/lib/pipeline.py", line 461, in execute
>     self.print_log()
>   File "/usr/local/lib/python3.7/site-packages/pvactools/lib/pipeline.py", line 93, in print_log
>     if past_inputs['pvactools_version'] != current_inputs['pvactools_version']:
> KeyError: 'pvactools_version'

I tried to find a solved issue but the most relevant I found was this https://github.com/griffithlab/pVACtools/issues/314 which did not solve the problem (it refers to installing the software via pip which brings me back to the original issue I opened).

**Comment by ArisStefanosSn** [comment] 2022-09-13 16:19
oh ok, that worked. Thank you! I need to annotate my VCF with VEP. I suppose this is not included in the Docker image and I need to install VEP as in here http://useast.ensembl.org/info/docs/tools/vep/script/index.html, is that right?

**Comment by susannasiebert** [comment] 2022-09-13 16:23
That's correct. VEP provides their own docker images (https://hub.docker.com/r/ensemblorg/ensembl-vep). Please be advised that there are two VEP plugins that you need include with your VEP runs, which are required for pVACseq. Those are not part of the default VEP plugins and need to be installed/mounted manually. You can find more information [here](https://pvactools.readthedocs.io/en/latest/pvacseq/input_file_prep/vep.html).

**Comment by ArisStefanosSn** [comment] 2022-09-16 17:51
Hi [@susannasiebert](https://github.com/susannasiebert), thank you for all the previous help. I have been working with the docker images for vep annotation and pvacseq analysis but still I can't manage to make this work:

I followed the steps 1-4 from here https://pvactools.readthedocs.io/en/latest/pvacseq/input_file_prep/vep.html. I can see the Frameshift and Wildtype plugins (Wildtype.pm and Frameshift.pm) in the VEP_plugins/ folder.

I obtained the input.vcf via: 

> pvacseq download_example_data /path/to/output/folder'

It contains the following columns:
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  H_NJ-HCC1395-HCC1395

Then I switched to singularity and vep (I assume that I do not need to run the 'vcf-genotype-annotator'):

> singularity run /path/to/ensemble_vep/ensembl-vep_latest.sif vep -i /path/to/input.vcf \
> -o /path/to/output/folder//input_vep.vcf \
> --database --vcf --fields "Allele,Consequence,Feature_type,Feature" \
> --plugin Frameshift --plugin Wildtype --dir_plugins /path/to/folder/VEP_plugins 

I get this output (header lines omitted):

> HEADER
> HEADER
> ...
> HEADER
> #CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  H_NJ-HCC1395-HCC1395
> 2       217498305       .       T       TGCTGCC .       .       CSQ=GCTGCC|intron_variant&non_coding_transcript_variant|Transcript|ENST00000474063,GCTGCC|intron_variant&non_coding_transcript_variant|Transcript|ENST00000486365,GCTGCC|intron_variant&non_coding_transcript_variant|Transcript|ENST00000663562,GCTGCC|intron_variant&non_coding_transcript_variant|Transcript|ENST00000676082 GT:AD:BQ:SS:DP:DP2:TAR:TIR:TOR:DP50:FDP50:SUBDP50:FT    0/1:90:.:2:101:101:90,91:4,4:40,40:103.29:0.59:0:PASS

> 4       40434704        .       AGCGGCTGCGGCGGCTGCGGCC  A       .       .       CSQ=-|intron_variant|Transcript|ENST00000295971,-|intron_variant|Transcript|ENST00000381793,-|intron_variant|Transcript|ENST00000381795,-|downstream_gene_variant|Transcript|ENST00000505220,-|downstream_gene_variant|Transcript|ENST00000505414,-|downstream_gene_variant|Transcript|ENST00000507180,-|intron_variant&NMD_transcript_variant|Transcript|ENST00000510871,-|downstream_gene_variant|Transcript|ENST00000511598,-|downstream_gene_variant|Transcript|ENST00000511902,-|downstream_gene_variant|Transcript|ENST00000513473,-|intron_variant|Transcript|ENST00000514014,-|downstream_gene_variant|Transcript|ENST00000514782,-|downstream_gene_variant|Transcript|ENST00000515053,-|intron_variant&non_coding_transcript_variant|Transcript|ENST00000515809        GT:AD:BQ:SS:DP:DP2:TAR:TIR:TOR:DP50:FDP50:SUBDP50:FT    0/1:125:.:2:128:128:125,125:5,5:12,12:119.5:1.75:0:PASS
> 

The columns look the same, so I assume that the input.vcf you provide is already eep-annotated (?). Then, I am running pvacseq as:

> singularity run /path/to/pvactools_latest.sif pvacseq run /path/to/input_vep.vcf \
> Test \
> HLA-A*02:01,HLA-B*35:01,DRB1*11:01 \
> MHCflurry MHCnuggetsI MHCnuggetsII NNalign NetMHC PickPocket SMM SMMPMBEC SMMalign \ 
> /path/to/output/folder/  \
> -e1 8,9,10,11 -e2 15 \
> --iedb-install-directory /path/to/IEDB

I am still getting:

> No MHC class I prediction algorithms chosen. Skipping MHC class I predictions.
> Executing MHC Class II predictions
> Converting .vcf to TSV
> /usr/local/lib/python3.7/site-packages/vcfpy/header.py:288: DuplicateHeaderLineWarning: Seen FILTER header more than once: PASS, using firstoccurence
>   DuplicateHeaderLineWarning,
> VCF doesn't contain VEP FrameshiftSequence annotations. Please re-annotate the VCF with VEP and the Wildtype and Frameshift plugins.
> 

What am I doing wrong? Is it something on the VEP step? Do you have any template on how the VEP-annotated file for pvacseq analysis should look like please? Thank you!

**Comment by susannasiebert** [comment] 2022-09-16 18:04
Yes, the problem is with your vep annotation step. If you check the CDQ header you will see that no annotations for these plugins were written.  VEP should’ve output something warning switch more information. I assume it’s unable to find the vep plugins directory. I’m unfamiliar with singularity though. Do you need to mount the volume that this directory is on?

**Comment by susannasiebert** [comment] 2022-10-06 13:57
Hi @ArisStefanosSn,
Were you able to resolve your VEP issue and get a successful pVACseq run?

**Comment by ArisStefanosSn** [comment] 2022-10-07 15:23
Hello @susannasiebert,

Sorry I did not reply earlier. Yes, I managed to run it successfully for mouse. Thank you very much for the support.

**Comment by susannasiebert** [comment] 2022-10-10 14:07
Wonderful. I'll close this issue then.

**Closed by susannasiebert** 2022-10-10 14:07 UTC

**Comment by QianhuiXu** [comment] 2022-11-02 12:15
I solved this error by using python2 to run configure

**Comment by QianhuiXu** [comment] 2022-11-02 12:15
I solved thise error by using python2 to run configure
