### ISSUE TITLE
Numerous dbus-daemon process when running pvacseq

### ISSUE THREAD

**Issue by mikisvaz** [griffithlab/pVACtools#410] opened 2019-06-14 17:59 UTC
* pvactools version: 1.4.2
* Python version: 3.5 (conda)
* Operating System: OpenSuse

**Describe the bug**
Running PVacSeq with several threads leaves dangling dbus-daemon processes that end up clogging the machine and preventing new threads to launch due to user limits

**To Reproduce**
```
env MHCFLURRY_DOWNLOADS_DIR=/home/mvazque2/.rbbt/share/databases/mhcflurry pvacseq run '/hom
e/mvazque2/.rbbt/var/jobs/VEP/analysis/SAMPLE_47cf35b96b0495bfd1eeb09a2dbe9743.vcf' 'SAMPLE' HLA-A*25:01,HLA-A*30:02,HLA
-B*18:01,HLA-C*12:03,HLA-C*05:09,HLA-DQB1*06:02,HLA-DQB1*03:05,HLA-DRB1*15:01,HLA-DRB1*04:03,HLA-DPA1*01:03,HLA-DPB1*04:01,HLA-DPB
1*138:01,HLA-DQA1*01:02,HLA-DQA1*03:01,HLA-G*01:01,HLA-DMA*01:01,HLA-DMB*01:01,HLA-DOA*01:01,HLA-DOB*01:01,HLA-DRA*01:02,HLA-DRA*0
1:01,HLA-E*01:01,HLA-E*01:03,HLA-F*01:01,HLA-H*01:02,HLA-H*01:01,HLA-J*01:01,HLA-MICA*018:01,HLA-MICB*005:02,HLA-MICB*002:01,HLA-T
AP1*01:01,HLA-TAP2*02:01,HLA-TAP2*01:04,HLA-V*01:01,HLA-L*01:01,HLA-L*01:02,HLA-A*26:01,HLA-C*05:01 MHCflurry NNalign NetMHC NetMHCcons NetMHCpan PickPocket SMM SMMPMBEC SMMalign '/home/mvazque2/.rbbt/var/jobs/PVacSeq/analysis/SAMPLE_a23f103568d537c7efdac
cce661de4b5.tsv.files/output' --iedb-install-directory /home/mvazque2/.rbbt/software/opt/IEDB/mhc_i/.. --normal-sample-name SAMPLE_NORMAL -t 20 --netmhc-stab --pass-only -e 8,9,10 --binding-threshold 1000000
```

I cannot send the original files, sorry, its sentible information
**Log Output**
$ ps -A|grep dbus
```
 1612 ?        00:00:00 dbus-daemon
 1705 ?        00:00:04 dbus-daemon
 8165 ?        00:00:00 dbus-daemon
 8772 ?        00:00:00 dbus-daemon
 9774 ?        00:00:00 dbus-daemon
10235 ?        00:00:00 dbus-daemon
10311 ?        00:00:00 dbus-daemon
10331 ?        00:00:00 dbus-daemon
10363 ?        00:00:00 dbus-daemon
10374 ?        00:00:00 dbus-daemon
10377 ?        00:00:00 dbus-daemon
10459 ?        00:00:00 dbus-daemon
10499 ?        00:00:00 dbus-daemon
10523 ?        00:00:00 dbus-daemon
10525 ?        00:00:00 dbus-daemon
10541 ?        00:00:00 dbus-daemon
10572 ?        00:00:00 dbus-daemon
10576 ?        00:00:00 dbus-daemon
10621 ?        00:00:00 dbus-daemon
10673 ?        00:00:00 dbus-daemon
10674 ?        00:00:00 dbus-daemon
10706 ?        00:00:00 dbus-daemon
10707 ?        00:00:00 dbus-daemon
10709 ?        00:00:00 dbus-daemon
11361 ?        00:00:00 dbus-daemon
12199 ?        00:00:00 dbus-daemon
14342 ?        00:00:00 dbus-daemon
15895 ?        00:00:00 dbus-daemon
22969 ?        00:00:00 dbus-daemon
23127 ?        00:00:00 dbus-daemon
24173 ?        00:00:00 dbus-daemon
26867 ?        00:00:00 dbus-daemon
28876 ?        00:00:00 dbus-daemon
31219 ?        00:00:00 dbus-daemon
32436 ?        00:00:00 dbus-daemon
32542 ?        00:00:00 dbus-daemon
32745 ?        00:00:00 dbus-daemon
35952 ?        00:00:00 dbus-daemon
37343 ?        00:00:00 dbus-daemon
37811 ?        00:00:00 dbus-daemon
```

**Output File**
If your bug is related to the contents of an output file, please paste the output file here.

**Expected behavior**
I believe not so many dbus-daemon process should spawn or at least they should be removed.

**Comment by susannasiebert** [comment] 2019-06-17 14:21
Unfortunately, I'm unable to reproduce this issue using our latest docker image for testing. Could this problem be specific to your system?

**Comment by susannasiebert** [comment] 2019-07-10 13:25
I'm closing this issue since there hasn't been any more activity. Please feel free to reopen if you'd like further assistance with this problem.

**Closed by susannasiebert** 2019-07-10 13:25 UTC
Labels: question
