### ISSUE TITLE
pVACseq's phasing feature related .vcf to .csv conversion error

### ISSUE THREAD

**Issue by jasonwalker80** [griffithlab/pVACtools#236] opened 2018-12-14 20:43 UTC
Created on behalf of: Eugine Levin
Received: Wednesday, December 12, 2018 at 3:55 AM
Via: pVAC-Seq Support Email List

* pvactools version: NA
* Python version: NA
* Operating System: NA

**Describe the bug**
I have been continuously running into error during testing pVacseq's phasing feature. It runs okay without the feature introduced. To my understanding, it seems to be related to conversion of VCF file into tab-separated table. Because no similar problem has been described by community, I thought it may be the case to write to you for assist. 

**To Reproduce**
```
pvacseq run vep_only_1.vcf OUTPUT $hla NetMHC NetMHCIIpan /tmp -e 8,9,10,11 --net-chop-method cterm --netmhc-stab \
  --normal-cov 0 --tdna-cov 0 --trna-cov 0 --normal-vaf 100 --tdna-vaf 0 --trna-vaf 0 --expn-val 0 --net-chop-threshold 0 \
    -m median -d full -k --iedb-install-directory /soft \
--phased-proximal-variants-vcf phased_only_1.vcf.gz -k -i additional_input_file_list.yaml
```

**Log Output**
```
Converting .vcf to TSV
Warning: There are multiple CSQ entries (consequences) for proximal variant Record(CHROM=chr1, POS=171540670, REF=G, ALT=[T]) and alternate allele T. Using the first one.
Segmentation fault (core dumped)
```

**Output File**
NA

**Expected behavior**
Please let me know if you have any clue what should be done to fix this one.
I would appreciate any suggestions

**Comment by jasonwalker80** [comment] 2018-12-14 20:57
>  Hi Eugine,
> 
> Thanks for using pVACtools!
> 
> I appreciate the detailed example including example data. A few additional questions:
> Which version of pVACtools are you using? 
> Which version of Python? 
> What is your Operating System?
> 
> I created a bug report on GitHub:
> https://github.com/griffithlab/pVACtools/issues/236
> 
> The first thing I noticed in your VEP VCF file, is that the sample name does not match the sample name in the phased VCF. It looks like a genotype string, ex. “0/1:” was prepended to the sample name. I’m not sure if this caused the segmentation fault, but it’s something to consider fixing with the methods used to generate the VCF.
> 
> We will continue to investigate this issue once we have the requested information.
> 
> Thanks,
> Jason

**Comment by susannasiebert** [comment] 2019-01-07 15:43
I believe the problem is that you are using the unzipped version of your input VCF. You need to bgzip `vep_only_1.vcf` and the tabix index it. Please see https://pvactools.readthedocs.io/en/latest/pvacseq/input_file_prep/proximal_vcf.html#bgzip-and-index-the-input-vcf for further instructions.

**Comment by susannasiebert** [comment] 2019-01-17 16:14
Version 1.2.0 adds a fatal message when using the phasing feature with an unzipped input VCF. Resolving.

**Closed by susannasiebert** 2019-01-17 16:14 UTC
