### ISSUE TITLE
ImportError: cannot import name 'Reader' from 'parser' 

### ISSUE THREAD

**Issue by dhy2002** [griffithlab/pVACtools#905] opened 2023-02-19 04:17 UTC
When I run pvacseq, the following import error pops up.
<img width="330" alt="image" src="https://user-images.githubusercontent.com/100278952/219921869-5214b8c2-af90-45e5-a00e-febbfd7a93e2.png">
Can you help to solve it?
Thanks!

**Comment by susannasiebert** [comment] 2023-02-20 15:12
Please fill out the full bug report template in order for us to further investigate this problem. When filling out this template please ensure to include the _full_ error stack trace. In addition, please include a list of all installed packages and their versions, which can be obtained by running `pip freeze`.

* pvactools version:
* Python version:
* Operating System:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
What is the pVACtools command you ran? Please also attach any input files that can be used to reproduce this problem.

**Log Output**
```
The log that gets written to standard out
```

**Output File**
If your bug is related to the contents of an output file, please paste the output file here.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Comment by dhy2002** [comment] 2023-02-21 03:23
The following is my python and pvactools version
<img width="951" alt="image" src="https://user-images.githubusercontent.com/100278952/220237483-21183bde-9f7d-4e01-92f8-15ecece44cfd.png">
and the operating system is linux64

The bug pops up when I simple input "pvacseq run"
and it seems that package "Reader" cannot be found:
Traceback (most recent call last):
  File "/gpfs/share/home/2000011040/miniconda3/bin/pvacseq", line 5, in <module>
    from tools.pvacseq.main import main
  File "/gpfs/share/home/2000011040/miniconda3/lib/python3.9/site-packages/tools/pvacseq/__init__.py", line 15, in <module>
    from . import *
  File "/gpfs/share/home/2000011040/miniconda3/lib/python3.9/site-packages/tools/pvacseq/run.py", line 4, in <module>
    from lib.prediction_class import *
  File "/gpfs/share/home/2000011040/miniconda3/lib/python3.9/site-packages/lib/__init__.py", line 27, in <module>
    from . import *
  File "/gpfs/share/home/2000011040/miniconda3/lib/python3.9/site-packages/lib/input_file_converter.py", line 1, in <module>
    import vcf
  File "/gpfs/share/home/2000011040/miniconda3/lib/python3.9/site-packages/vcf/__init__.py", line 166, in <module>
    from parser import Reader, Writer
ImportError: cannot import name 'Reader' from 'parser' (/gpfs/share/home/2000011040/miniconda3/lib/python3.9/lib-dynload/parser.cpython-39-x86_64-linux-gnu.so)

and all the packages installed are listed below:
absl-py==1.2.0
alabaster==0.7.12
altair==4.2.0
aniso8601==9.0.1
anndata==0.7.8
appdirs==1.4.4
astroid==2.14.2
astropy==5.2.1
astunparse==1.6.3
attrs==21.4.0
Babel==2.9.1
beautifulsoup4==4.11.2
biopython==1.76
bokeh==0.13.0
boto3==1.7.84
botocore==1.10.84
brotlipy==0.7.0
cached-property==1.5.2
cachetools==5.2.0
CellPhoneDB==2.1.7
certifi==2021.10.8
cffi @ file:///opt/conda/conda-bld/cffi_1642701102775/work
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
click==6.7
clickclick==20.10.2
colorama==0.4.4
coloredlogs==15.0.1
colormath==3.0.0
commonmark==0.9.1
conda==4.12.0
conda-package-handling @ file:///tmp/build/80754af9/conda-package-handling_1618262147379/work
connexion==1.4.2
cryptography @ file:///tmp/build/80754af9/cryptography_1639414572950/work
cutadapt==4.0
cycler @ file:///tmp/build/80754af9/cycler_1637851556182/work
Cython @ file:///tmp/build/80754af9/cython_1647850345254/work
datacache==1.2.1
dill==0.3.6
dnaio==0.8.1
docutils==0.17.1
entrypoints==0.4
fbpca==1.0
feedparser==6.0.10
Flask==1.0.4
Flask-Cors==3.0.10
Flask-RESTful==0.3.9
Flask-Testing==0.7.1
flatbuffers==1.12
fonttools==4.29.1
future @ file:///home/conda/feedstock_root/build_artifacts/future_1649010145299/work
gast==0.4.0
geosketch==0.3
google-auth==2.9.1
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.47.0
gtfparse==1.3.0
h5py==3.7.0
humanfriendly==10.0
idna @ file:///tmp/build/80754af9/idna_1637925883363/work
igraph==0.9.9
imagesize==1.3.0
importlib-metadata==4.11.2
inflection==0.5.1
iniconfig==1.1.1
isal==0.11.1
iso8601==1.1.0
isort==5.12.0
isovar==1.1.1
itsdangerous==2.1.2
Jinja2==3.0.3
jmespath==0.10.0
joblib @ file:///tmp/build/80754af9/joblib_1635411271373/work
jsonschema==2.6.0
keras==2.9.0
Keras-Preprocessing==1.1.2
kiwisolver @ file:///opt/conda/conda-bld/kiwisolver_1638569886207/work
lazy-object-proxy==1.9.0
libclang==14.0.6
llvmlite==0.38.0
loompy==3.0.7
louvain==0.7.1
lzstring==1.0.4
Markdown==3.3.6
MarkupSafe==2.1.0
matplotlib @ file:///tmp/build/80754af9/matplotlib-suite_1647441664166/work
mccabe==0.7.0
memoized-property==1.0.3
mhcflurry==2.0.6
mhcgnomes==1.8.4
mhcnames==0.4.8
mhcnuggets==2.4.0
mhctools==1.8.1
mkl-fft==1.3.1
mkl-random @ file:///tmp/build/80754af9/mkl_random_1626186066731/work
mkl-service==2.4.0
mock==5.0.1
multiqc==1.12
munkres==1.1.4
natsort==8.1.0
networkx==2.6.3
nose==1.3.7
novosparc==0.4.3
np-utils==0.6.0
numba==0.55.1
numexpr==2.8.1
numpy==1.21.5
numpy-groupies==0.9.14
oauthlib==3.2.0
opt-einsum==3.3.0
ordereddict==1.1
packaging @ file:///tmp/build/80754af9/packaging_1637314298585/work
pandas==1.5.3
patsy==0.5.2
pdfkit==1.0.0
pika==0.12.0
Pillow==9.0.1
platformdirs==3.0.0
pluggy==1.0.0
POT==0.8.1.0
progressbar33==2.4
protobuf==3.19.4
psutil==5.9.4
pvactools==2.0.1
py==1.11.0
py-postgresql==1.3.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pybktree==1.1
pycosat==0.6.3
pycparser @ file:///tmp/build/80754af9/pycparser_1636541352034/work
pyensembl==2.2.8
pyerfa==2.0.0.1
Pygments==2.11.2
pylint==2.16.2
pymp-pypi==0.5.0
pynndescent==0.5.6
pyOpenSSL @ file:///opt/conda/conda-bld/pyopenssl_1643788558760/work
pypandoc==1.10
pyparsing==3.0.7
PyQt5==5.15.6
PyQt5-Qt5==5.15.2
PyQt5-sip==12.10.1
pyrsistent==0.18.1
pysam==0.18.0
PySocks @ file:///tmp/build/80754af9/pysocks_1605305812635/work
pytest==7.1.1
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1647961439546/work
PyVCF==0.4.3
PyVCF3==1.0.3
PyYAML==5.4
reader==3.4
recommonmark==0.7.1
regex==2022.3.15
requests @ file:///opt/conda/conda-bld/requests_1641824580448/work
requests-oauthlib==1.3.1
rich==11.2.0
roman==3.3
rpy2==3.0.5
rsa==4.9
ruamel-yaml-conda @ file:///tmp/build/80754af9/ruamel_yaml_1616016711199/work
s3transfer==0.1.13
scanpy==1.9.1
scikit-learn==0.22
scipy==1.8.0
scvelo==0.2.4
seaborn==0.11.2
sercol==0.1.4
serializable==0.2.1
session-info==1.0.0
sgmllib3k==1.0.0
shellinford==0.4.1
simanneal==0.5.0
simplegeneric==0.8.1
simplejson==3.17.6
simplesam==0.1.4.0
sinfo==0.3.4
sip==4.19.13
six @ file:///tmp/build/80754af9/six_1644875935023/work
snowballstemmer==2.2.0
soupsieve==2.4
spectra==0.0.11
Sphinx==4.5.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
SQLAlchemy==1.3.24
statsmodels==0.13.2
stdlib-list==0.8.0
swagger-spec-validator==2.1.0
tables==3.7.0
tensorboard==2.9.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.9.1
tensorflow-estimator==2.9.0
tensorflow-io-gcs-filesystem==0.26.0
termcolor==1.1.0
texttable==1.6.4
threadpoolctl==3.1.0
tinytimer==0.0.0
tomli==2.0.1
tomlkit==0.11.6
toolz==0.11.2
tornado==5.0.2
tqdm==4.32.2
typechecks==0.1.0
typing_extensions==4.1.1
umap-learn==0.5.2
umi-tools==1.1.2
urllib3 @ file:///opt/conda/conda-bld/urllib3_1643638302206/work
varcode==1.1.0
vaxrank==1.4.0
velocyto==0.17.17
watchdog==2.2.1
Werkzeug==2.1.0
wget==3.2
wrapt==1.14.1
xlrd==1.2.0
XlsxWriter==3.0.8
xopen==1.5.0
xvfbwrapper==0.2.9
zipp==3.7.0

Thanks a lot for your reply!

**Comment by susannasiebert** [comment] 2023-02-21 15:09
The version of pVACtools you are using is quite old. Could you try upgrading to the latest version of pVACtools (3.1.1)? I would also try an older version of python (e.g. 3.7) because I think there are some incompatibilities with 3.9 and above.

Alternatively, we also recommend our [Docker containers](https://pvactools.readthedocs.io/en/latest/install.html#docker-and-cwl) since they will prevent these sort of installation/import errors.

**Comment by dhy2002** [comment] 2023-02-22 01:06
If I create a new conda environment with python3.7, I cannot successfully install any version of pvactools, just as following shows.

Collecting pysam
  Using cached pysam-0.20.0.tar.gz (4.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [32 lines of output]
      # pysam: no cython available - using pre-compiled C
      # pysam: htslib mode is shared
      # pysam: HTSLIB_CONFIGURE_OPTIONS=None
      # pysam: (sysconfig) CC=gcc -pthread -B /gpfs/share/home/2000011040/miniconda3/envs/pvactest/compiler_compat -Wl,--sysroot=/
      # pysam: (sysconfig) CFLAGS=-Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC
      # pysam: (env) LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,/gpfs/share/home/2000011040/miniconda3/lib -Wl,-rpath-link,/gpfs/share/home/2000011040/miniconda3/lib -L/gpfs/share/home/2000011040/miniconda3/lib
      checking for gcc... gcc -pthread -B /gpfs/share/home/2000011040/miniconda3/envs/pvactest/compiler_compat -Wl,--sysroot=/
      checking whether the C compiler works... no
      configure: error: in `/tmp/pip-install-8sjweqha/pysam_9a51412bd10545aaa455d37745e1cf0f/htslib':
      configure: error: C compiler cannot create executables
      See `config.log' for more details
      checking for gcc... gcc -pthread -B /gpfs/share/home/2000011040/miniconda3/envs/pvactest/compiler_compat -Wl,--sysroot=/
      checking whether the C compiler works... no
      configure: error: in `/tmp/pip-install-8sjweqha/pysam_9a51412bd10545aaa455d37745e1cf0f/htslib':
      configure: error: C compiler cannot create executables
      See `config.log' for more details
      /bin/sh: ./hts_probe_cc.sh: No such file or directory
      Makefile:131: htscodecs.mk: No such file or directory
      make: *** [Makefile:120: htscodecs.mk] Error 127
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8sjweqha/pysam_9a51412bd10545aaa455d37745e1cf0f/setup.py", line 381, in <module>
          htslib_make_options = run_make_print_config()
        File "/tmp/pip-install-8sjweqha/pysam_9a51412bd10545aaa455d37745e1cf0f/setup.py", line 79, in run_make_print_config
          stdout = subprocess.check_output(["make", "-s", "print-config"])
        File "/gpfs/share/home/2000011040/miniconda3/envs/pvactest/lib/python3.7/subprocess.py", line 376, in check_output
          **kwargs).stdout
        File "/gpfs/share/home/2000011040/miniconda3/envs/pvactest/lib/python3.7/subprocess.py", line 468, in run
          output=stdout, stderr=stderr)
      subprocess.CalledProcessError: Command '['make', '-s', 'print-config']' returned non-zero exit status 2.
      # pysam: htslib configure options: None
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.




And when I try to upgrade pvactools with the command "pip install pvactools --upgrade", the version doesn't change at all. But if I use pip install pvactools==3.1.1, the version of tensorflow seems to conflict:

Collecting pvactools==3.1.1
  Using cached pvactools-3.1.1-py3-none-any.whl (10.0 MB)
Collecting keras==2.4.3
  Using cached Keras-2.4.3-py2.py3-none-any.whl (36 kB)
Requirement already satisfied: protobuf==3.19.4 in ./miniconda3/lib/python3.9/site-packages (from pvactools==3.1.1) (3.19.4)
Requirement already satisfied: biopython==1.76 in ./miniconda3/lib/python3.9/site-packages (from pvactools==3.1.1) (1.76)
Requirement already satisfied: pandas in ./miniconda3/lib/python3.9/site-packages (from pvactools==3.1.1) (1.5.3)
Collecting mhcnuggets==2.3.3
  Using cached mhcnuggets-2.3.3.tar.gz (33.1 MB)
Collecting testfixtures
  Using cached testfixtures-7.1.0-py3-none-any.whl (102 kB)
ERROR: Could not find a version that satisfies the requirement tensorflow==2.2.2 (from pvactools) (from versions: 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.7.0rc0, 2.7.0rc1, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.8.0rc0, 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.12.0rc0)
ERROR: No matching distribution found for tensorflow==2.2.2

I am sorry that I use the HPC of our school, so I have no authority to use docker.

**Comment by susannasiebert** [comment] 2023-02-22 15:56
The first issue might be fixed by installing Cython. However, with system-specific installation problems like these we highly recommend switching to our Docker containers.

**Comment by susannasiebert** [comment] 2023-03-07 15:35
Closing this issue due to inactivity but feel free to reopen if you're still running into problems after switching to Docker.

**Closed by susannasiebert** 2023-03-07 15:35 UTC
