### ISSUE TITLE
python3.8  pip install pvactools  ERROR

### ISSUE THREAD

**Issue by darkmoon1991** [griffithlab/pVACtools#819] opened 2022-07-06 07:15 UTC
I followed the instructions but find these errors
![image](https://user-images.githubusercontent.com/53558944/177491788-08eb5f41-4226-4abb-807b-f68fd6c606dc.png)
![image](https://user-images.githubusercontent.com/53558944/177491609-0b6e89b9-4310-47ff-ab88-44b45f067c71.png)

**Comment by susannasiebert** [comment] 2022-07-06 14:27
Thank you for your interest in pVACtools. I apologize for the issues you're running into with installing our tool. This is, unfortunately, a side effect of our dependency on vaxrank/varcode, which in turn still uses vcfpy (see https://github.com/openvax/varcode/issues/247). vcfpy cannot be installed with setuptools 58+ due to the deprecated usage of use_2to3 as described in #712. The solution would be to downgrade setuptools to an older version that still supports use_2to3. If that is not possible, we recommend using one of our docker containers.

I'm closing this issue as a duplicate of #712.

**Closed as completed by susannasiebert** 2022-07-06 14:27 UTC
Labels: duplicate
