### ISSUE TITLE
Test results for pVAC-Seq are empty

### ISSUE THREAD

**Issue by serge2016** [griffithlab/pVACtools#359] opened 2019-04-11 10:28 UTC
Hello!
I'm trying to understand if my installation of pvacseq (pvactools) works fine. So tried to run tests and check results.
Here are 2 things I found:
1. It's not obvious to find any instructions of how to test the installation. Could you provide any link to such instruction, please?
2. File `tests/test_data/pvacseq/MHC_Class_I/Test.filtered.tsv` and the next one `Test.filtered.condensed.ranked.tsv` do not contain any results.

More over, I am not sure, if the input file `tests/test_data/pvacseq/input.vcf` is properly VEP-annotated. Also this file seems to be generated using 37 version of human genome, not 38.

**Comment by susannasiebert** [comment] 2019-04-11 13:25
1) You can find our documentation at pvactools.org. Particularly, you might want to check out the Getting Started section here (https://pvactools.readthedocs.io/en/latest/pvacseq/getting_started.html).
2) That particular test is more of an integration test to ensure that all of the steps run as expected. In this particular case all epitopes were filtered out.

What specifically is your concern with the existing VEP annotation of that test VCF file? These test files have been around for a few years and we haven't seen a reason to upgrade them to a build 38 version. pVACseq works on both build 37 and 38 VCFs.

**Comment by serge2016** [comment] 2019-04-11 13:31
Ok, is there any example data (vcf-file) with pVAC-Seq run results on it in the repo or in any other location?

Maybe all epitopes were filtered out in this particular case due to not proper VEP-annotation?

And how I can run integration tests?

**Comment by susannasiebert** [comment] 2019-04-11 13:38
In the repo, the example data is located here:https://github.com/griffithlab/pVACtools/tree/master/tools/pvacseq/example_data. You can download it on the command line by running `pvacseq download_example_data` (https://pvactools.readthedocs.io/en/latest/pvacseq/additional_commands.html#example-data).

No, the epitopes simply didn't pass the set of filters that pVACseq runs as part of its pipeline. See https://pvactools.readthedocs.io/en/latest/pvacseq/filter_commands.html for a list of filters that are run by pVACseq. You can also run these filters manually on the all_epitopes file to reproduce this behavior.

We don't have a command to run the tests from an installation. You can run it from the repo with `TEST_FLAG=1 python -m unittest discover`.

**Comment by serge2016** [comment] 2019-04-11 13:41
@susannasiebert thank you! I'll try to reproduce the Getting Started section.

Are these steps required to run pvacseq or they are needed for more precise results?
 - Adding coverage data to your VCF
 - Adding expression data to your VCF
 - Creating a phased VCF of proximal variants

**Comment by susannasiebert** [comment] 2019-04-11 13:50
These three steps are not required but highly recommended. Adding coverage and expression data will allow pVACseq to filter on read depth, VAF, transcript and gene expression, which will eliminate "bad" epitopes that would otherwise remain in the filtered file. 

Adding a phased VCF of proximal variants will create more precise results. Providing such a file will incorporate proximal variants that are in phase with a somatic variant of interest into the epitope prediction. Otherwise some epitope sequences might be incorrect because they don't incorporate their proximal variants. Unfortunately, this step right now only incorporates proximal missense variants so if the proximal variant is an indel, the epitope would still be incorrect. This is why, in all cases, we recommend manually inspecting filtered epitopes, for example using IGV, to confirm that the predicted epitope for the location is correct before using the pVACseq results in any downstream processing, like pVACvector vaccine design. For more information you might be interested in our proximal variant paper we recently published in Nature Genetics (https://www.nature.com/articles/s41588-018-0283-9)

**Comment by susannasiebert** [comment] 2019-04-16 14:53
I'm closing this issue since I believe I answered all of your questions but feel free to reopen (or make a new issue) should you have any additional questions.

**Closed by susannasiebert** 2019-04-16 14:53 UTC
Labels: question
