### ISSUE TITLE
pVAC-Seq stuck without error message

### ISSUE THREAD

**Issue by carolinamelo** [griffithlab/pVACtools#226] opened 2018-11-27 18:22 UTC
* pvactools version: 1.1.2
* Python version: 3.5.6
* Operating System: Debian GNU/Linux 8 

**Describe the bug**
While running pvacseq on my WES sample it gets stuck as soon as it starts the entries 201-400, without any error message. Simply don't go ahead. I've tried different times and always get stuck at the same point. I ran the same command line on other 10 samples and worked fine. It is happen only with this one. It goes through the 6 HLA-alleles and the 3 peptides length for the entries 1-200, but it gets stuck on the first allele and peptide length for the entries 201-400.

**To Reproduce**
pvacseq run SJBALL020980_vep_output.readcount.tx.vcf SJBALL020980_D1_EXCAP HLA-A*26:01,HLA-A*33:01,HLA-B*14:01,HLA-B*52:01,HLA-C*12:02,HLA-C*08:02 NetMHCcons ./pvacseq --iedb-install-directory /home/BIG/CMelo -e 8,9,10 --net-chop-method cterm --netmhc-stab --top-score-metric=lowest --tdna-vaf 0.25 --expn-val 1 --tdna-cov 10 -c 1 --pass-only --keep-tmp-files

**Log Output**

[inputs.zip](https://github.com/griffithlab/pVACtools/files/2621301/inputs.zip)

**Output File**
[erro_pvacseq.txt](https://github.com/griffithlab/pVACtools/files/2621278/erro_pvacseq.txt)

**Expected behavior**
I expected it goes through all the Variant Peptide FASTA and Key Files, but it gets stuck as soon as it starts the second Key File.

**Comment by susannasiebert** [comment] 2018-12-03 15:01
Unfortunately, without having the actual input VCF, it is difficult to pinpoint why you might be running into this problem. I would start by inspecting the fasta file that corresponds to the chunk that is getting stuck. Are there any very long sequences in that file? If so, you might want to try reducing the `--downstream-sequence-length` (if the offending sequence is from a frameshift) or reducing the `--fasta-size` (if the problem is related to large indels). Runtime for each chunk is directly related to the number of epitopes of all the sequences in the fasta file getting processed so this would be my first guess as to what is causing this chunk to "hang", i.e., needing long processing times.

**Comment by carolinamelo** [comment] 2018-12-03 18:04
Hi Susanna!I will attach the VCF file again. The time it hangs is more than 24 hours. Indeed, I waited for two days and then gave up.Thank you!

    Em segunda-feira, 3 de dezembro de 2018 13:01:59 BRST, Susanna Kiwala <notifications@github.com> escreveu:  
 
 
Unfortunately, without having the actual input VCF, it is difficult to pinpoint why you might be running into this problem. I would start by inspecting the fasta file that corresponds to the chunk that is getting stuck. Are there any very long sequences in that file? If so, you might want to try reducing the --downstream-sequence-length (if the offending sequence is from a frameshift) or reducing the --fasta-size (if the problem is related to large indels). Runtime for each chunk is directly related to the number of epitopes of all the sequences in the fasta file getting processed so this would be my first guess as to what is causing this chunk to "hang", i.e., needing long processing times.

**Comment by carolinamelo** [comment] 2018-12-03 18:12
[SJBALL020980_vep_output.readcount.tx.zip](https://github.com/griffithlab/pVACtools/files/2640667/SJBALL020980_vep_output.readcount.tx.zip)

**Comment by susannasiebert** [comment] 2018-12-03 18:13
@carolinamelo if you're having trouble uploading the VCF to GitHub you may also email it to us at help@pvactools.org.

**Comment by susannasiebert** [comment] 2018-12-03 21:01
As suspected, one of the variants in the second fasta file is a frameshift with a very long downstream sequence. Try reducing the `--downstream-sequence-length` to a lower number to reduce the processing time. The default is 1000.

**Comment by carolinamelo** [comment] 2018-12-04 12:20
Hi Susanna!
You were right! It worked now!
Thank you once again! And congratulations for such useful tool! 
All the best!

**Comment by susannasiebert** [comment] 2018-12-04 14:48
Glad to hear this fixed this problem. I'm resolving this issue.

**Closed by susannasiebert** 2018-12-04 14:48 UTC
