### ISSUE TITLE
ERROR: mismatch b.t actual and expected amino acid sequence

### ISSUE THREAD

**Issue by alongalor** [griffithlab/pVACtools#284] opened 2019-02-11 21:49 UTC
* pvactools version:  1.3.0
* Python version: 3.5.5
* Operating System: Linux

**Describe the bug**
```ERROR: There was a mismatch between the actual wildtype amino acid sequence (DGLAPPQHLIRVEGNLRVEYLDDR) and the expected amino acid sequence (DGEQLGLERRQGWLPRVPRPLIPH). Did you use the same reference build version for VEP that you used for creating the VCF?```

This error is surprising as I did use the same reference build version for VEP that was used to create the VCF.

**To Reproduce**
What is the pVACtools command you ran? Please also attach any input files that can be used to reproduce this problem.

```
pvacseq run \
xau.vcf \
xau \
HLA-A*02:07 \
MHCflurry MHCnuggetsI MHCnuggetsII \
xau \
-e 8,9,10,11
```

The input is available for download at: https://drive.google.com/file/d/16aKpVdX7J-7zBV6bohPEZestuO7q70jQ/view?usp=sharing. For reference, this file was produced by downloading the COSMIC Coding mutations file (from https://cancer.sanger.ac.uk/cosmic/download by clicking the button "Download Whole File" under the header "VCF Files (coding and non-coding mutations)", after registering), pasting the header and a 100,000 line segment of the file and annotating it with VEP as suggested in your documentation (as shown below):

```
vep \
--database \
--input_file xau.vcf \
--output_file xau.vcf \
--format vcf \
--vcf \
--symbol \
--terms SO \
--tsl \
--hgvs \
--fasta human_g1k_v37.fasta \
--offline \
--cache \
--plugin Downstream \
--plugin Wildtype \
--dir_plugins VEP_plugins \
--pick \
--dir_cache VEP_Cache \
--assembly GRCh37
```

**Log Output**
Attached below:
[slurm-33688544.out.txt](https://github.com/griffithlab/pVACtools/files/2853171/slurm-33688544.out.txt)

**Output File**
N/A

**Expected behavior**
To produce output as stipulated by program.

**Comment by chrisamiller** [comment] 2019-02-11 22:44
I've seen that error before when using VCFs lifted between reference builds. That is, places where the reference base has changed, such that what's in the REF field of the VCF doesn't match the reference (and hence, doesn't match the WT protein consequence)

My guess is that's what happened in cosmic as well, as it's been around forever, and has probab been lifted over a few times. 

If that turns out to be the case, you'll either need to:  a) fix the VCF to correct those ref bases or b) drop those sites.  (I'd probably write a little script that calls samtools faidx and compares the bases. You might also need to think about how to handle edge cases where the new ref is a "C" and the called variant is a "C"!)

**Comment by susannasiebert** [comment] 2019-02-12 15:10
@chrisamiller thank you for the comprehensive write up for this issue. Since this is not a bug with pVACseq but indeed intended behavior, I'm resolving this issue.

**Closed by susannasiebert** 2019-02-12 15:10 UTC

**Comment by alongalor** [comment] 2019-02-12 23:32
Thanks a lot @chrisamiller! Really appreciate your detailed response - it was very helpful in troubleshooting this :)
