### ISSUE TITLE
error about mismatch amino acid sequence

### ISSUE THREAD

**Issue by gudeqing** [griffithlab/pVACtools#731] opened 2021-11-03 07:37 UTC
Hi， I encountered the error as following. and I know that there are some description about issue. https://pvactools.readthedocs.io/en/latest/pvacseq/errors.html?highlight=mismatch#input-vcf-vep-annotation

Indeed, vep annotation and variant calling steps may used different reference genome. But I am quite sure that both used hg19 references as input.  I run pvacseq on more than 30 samples (which is processed by same pipeline) , and only met the error several times. AND I found these variants should not PASS filter since VCF.column.filter !="PASS”.  So, I am wondering  if there is an unknown bug in predicting amino acid sequence. Following are error image:

![image](https://user-images.githubusercontent.com/30919159/140022745-47084ed4-9b9e-4ae7-adb3-9378cb3fb2c7.png)

**Comment by susannasiebert** [comment] 2021-11-03 13:57
The problem is not the reference itself but the transcript nucleotide sequences from Ensembl, which might not match the reference you're using in some positions. If you would be able to share the full VCF entry for this position, as well as your header line for the CSQ info field, I can look into this more.

Our recommendation is to use the vatools ref-transcript-mistmatch-reproter to remove such entries since pVACseq is unable to process them: https://vatools.readthedocs.io/en/latest/ref_transcript_mismatch_reporter.html.

**Comment by susannasiebert** [comment] 2021-11-03 13:58
We should update our help docs to recommend this tool.

**Comment by gudeqing** [comment] 2021-11-04 10:28
Sorry that I cannot share you any postion information since I cannot copy anything out of the platform I am working on.  
And thanks for your recommendation.
The remained question is that I found the special mutation should not pass filters (because I had set --only_pass),  however, pvacseq is still processing this special site. So, does pvacseq generates fasta without considering any filters ?

**Comment by susannasiebert** [comment] 2021-11-04 13:51
The correct argument to set is `--pass-only`. If you specified `--only_pass` that wouldn't work but it should also fail the run altogether because an unknown argument was supplied. To check whether that argument was applied correctly to your run you can check the `inputs.yml` file in your `MHC_Class_I/log` output directory.

The `--pass-only` argument will only process variants that have `PASS` or `.` in the `FILTER` column of the VCF entry. You would need to check whether or not a filter was set in that column.

**Comment by susannasiebert** [comment] 2021-12-03 15:26
I'm closing this issue since there has been no further activity but please to reopen if you're still running into problems.

**Closed by susannasiebert** 2021-12-03 15:26 UTC
